### ISSUE TITLE
Representing the character data as JSON

### ISSUE THREAD

**Issue by ImportTaste** [Shadowth117/PSO2-Salon-Tool#10]
A staple of save editors, since saves can include all sorts of extraneous data, would be a section of the GUI that allows you to manually edit the data by representing it through JSON or something similar. Because there's still a lot that isn't yet part of the GUI, I think this important to implement.

The interpreter that converts the data to JSON could also be designed with forwards-compatibility in mind, making it so PSO2's future additions to the character data format would still (most likely) be handled correctly. You could make it so that if the GUI fails to load character data, it would still attempt to represent the data through JSON and allow it to be edited that way.

**Comment by Shadowth117** [comment]
This was something I considered a bit, but it's not something I've personally done before so I focused my efforts on just getting things working mainly. The tool does have decryption functionality for the files.

As far as generic JSON for whatever is spit out... I guess I'm curious to know how you would want that even handled. I'm not well versed in how save editors are typically handled so maybe this is rather standard, but the different versions of the format tend to shift data a decent bit without obvious ways to detect that. There's no pointers, tags, or anything for the exposed salon files, it's just all spit out at a set size Sega's parser expects based on the version. Comparable files for internal character data are variable with less and more things, ergo can't offer an accurate look at how exposed files should be past a base level.

If you have a suggestion on how to handle that other than just spitting out something that the user would probably be better off looking at in a hex editor for newer versions, I'm all ears. Otherwise, forward compatibility just can't happen in my eyes. General .json editing, maybe? It would be new for me.

**Comment by Shadowth117** [comment]
> A staple of save editors, since saves can include all sorts of extraneous data, would be a section of the GUI that allows you to manually edit the data by representing it through JSON or something similar. Because there's still a lot that isn't yet part of the GUI, I think this important to implement.
> 
> The interpreter that converts the data to JSON could also be designed with forwards-compatibility in mind, making it so PSO2's future additions to the character data format would still (most likely) be handled correctly. You could make it so that if the GUI fails to load character data, it would still attempt to represent the data through JSON and allow it to be edited that way.

Closing this as based on input from colleagues as forwards compatible .json isn't a realistic option for a format like this without the entire problem of analyzing the binary itself in the first place. Ergo, the stated purpose of adding this feature is unreasonable at this time. I won't rule it out for the future as a boredom project, but it's definitely not a critical feature.

As stated before the tool does offer a means of decrypting and re-encrypting binary data. I firmly believe given the variability of the data and lack of indicators that one would be better off doing format analysis based on that.
